# Generated by Django 5.2.17 on 2026-09-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(db_index=True, max_length=64)),
                ('question', models.TextField()),
                ('statut', models.CharField(max_length=20)),
                ('reponse', models.JSONField()),
                ('duree_s', models.FloatField(blank=True, null=True)),
                ('origine_plan', models.CharField(blank=True, max_length=20)),
                ('indicateur', models.CharField(blank=True, max_length=60)),
                ('methode', models.CharField(blank=True, max_length=30)),
                ('epingle', models.BooleanField(default=False, help_text='Question de démonstration : jamais purgée du cache.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisee', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['empreinte', 'statut'], name='api_requete_emprein_4b492e_idx'), models.Index(fields=['-cree_le'], name='api_requete_cree_le_f30611_idx')],
            },
        ),
    ]
