# Generated by Django 5.2.17 on 2026-09-18 23:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.CharField(max_length=200, unique=True)),
                ('empreinte', models.CharField(max_length=64)),
                ('lignes_lues', models.IntegerField(default=0)),
                ('zones_creees', models.IntegerField(default=0)),
                ('observations_creees', models.IntegerField(default=0)),
                ('charge_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-charge_le'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('plateforme', models.CharField(max_length=100)),
                ('date_extraction', models.DateField()),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('synonymes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None)),
                ('unite', models.CharField(max_length=40)),
                ('dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('agregeable', models.BooleanField(default=True)),
                ('granularite_geo_min', models.CharField(max_length=20)),
                ('frequence', models.CharField(choices=[('ponctuel', 'Ponctuel'), ('annuel', 'Annuel'), ('trimestriel', 'Trimestriel')], max_length=20)),
                ('comparaison_defaut', models.CharField(blank=True, choices=[('n-1', 'Année précédente'), ('t-4', 'Glissement annuel (T vs T-4)')], max_length=10, null=True)),
                ('prix_base', models.CharField(blank=True, max_length=40)),
                ('derive_de', models.CharField(blank=True, max_length=200)),
                ('niveau_sectoriel', models.CharField(blank=True, max_length=20)),
                ('secteur_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_secteurs', to='catalog.indicateur')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='catalog.source')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['granularite_geo_min'], name='catalog_ind_granula_483bbf_idx'), models.Index(fields=['frequence'], name='catalog_ind_frequen_1430a3_idx')],
            },
        ),
    ]
