# Generated by Django 5.2.17 on 2026-09-18 23:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(db_index=True, max_length=10)),
                ('dims', models.JSONField(blank=True, default=dict)),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=20)),
                ('chargement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.chargement')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.indicateur')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='geography.zone')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'indexes': [models.Index(fields=['indicateur', 'zone', 'periode'], name='obs_ind_zone_per'), models.Index(fields=['indicateur', 'periode'], name='obs_ind_per'), django.contrib.postgres.indexes.GinIndex(fields=['dims'], name='obs_dims_gin')],
                'constraints': [models.UniqueConstraint(fields=('indicateur', 'zone', 'periode', 'dims'), name='observation_unique')],
            },
        ),
    ]
