# Generated by Django 5.2.17 on 2026-09-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('niveau', models.CharField(choices=[('region', 'Région'), ('departement', 'Département'), ('commune', 'Commune'), ('quartier', 'Quartier / Village / Hameau'), ('national', 'National')], max_length=20)),
                ('geojson_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('com_arrt_ville', models.CharField(blank=True, max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='geography.zone')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['niveau', 'nom'],
                'indexes': [models.Index(fields=['niveau'], name='geography_z_niveau_6b8096_idx'), models.Index(fields=['niveau', 'parent'], name='geography_z_niveau_1c4a4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'nom'), name='zone_unique_dans_parent')],
            },
        ),
    ]
